//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legado.Windows {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Legado.Windows.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [{
        ///        &quot;bookSourceComment&quot;: &quot;\u9876\u70b9\u5c0f\u8bf4 \u00b7 \u540c\u6b65\u8d77\u70b9/\u7eb5\u6a2a\u70ed\u95e8\u4e66 \u00b7 \u65e0\u5f39\u7a97 \u00b7 2025\u5e7412\u6708\u5b9e\u6d4b\u53ef\u7528&quot;,
        ///        &quot;bookSourceGroup&quot;: &quot;\u4e3b\u6d41\u805a\u5408\u6e90&quot;,
        ///        &quot;bookSourceName&quot;: &quot;\u9876\u70b9\u5c0f\u8bf4&quot;,
        ///        &quot;bookSourceType&quot;: 0,
        ///        &quot;bookSourceUrl&quot;: &quot;https://www.dingdian6.com&quot;,
        ///        &quot;customOrder&quot;: 0,
        ///        &quot;enabled&quot;: true,
        ///        &quot;enabledExplore&quot;: false,
        ///        &quot;enabledCookie [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string bs {
            get {
                return ResourceManager.GetString("bs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{
        ///        &quot;bookSourceComment&quot;: &quot;250101\u65b0\u589e\u756a\u8304\u6765\u6e90\n250203\u65b0\u589e\u4e03\u732b\u6765\u6e90\n250204\u65b0\u589e\u5f97\u95f4\u6765\u6e90\n250204\u65b0\u589eQQ\u6765\u6e90(\u4ec5\u652f\u6301\u514d\u8d39\u5c0f\u8bf4)\n250204\u65b0\u589e\u718a\u732b\u770b\u4e66\n250210\u66f4\u65b0\u65e5\u5fd7\uff1a\n1.\u91c7\u7528\u5168\u65b0\u9a8c\u8bc1\u65b9\u5f0f\uff0c\u4e4b\u540e\u672a\u586b\u5199\u5bc6\u94a5\uff0c\u53ef\u4ee5\u5728\u9605\u8bfb\u9875\u767b\u9646\u540e\u5237\u65b0\u9605\u8bfb\u98 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ts {
            get {
                return ResourceManager.GetString("ts", resourceCulture);
            }
        }
    }
}
